# $FreeBSD: src/sys/modules/s3/Makefile,v 1.4 2001/01/06 14:00:13 obrien Exp $

.PATH: ${.CURDIR}/../../dev/fb

KMOD=	s3
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h \
	s3_pci.c

.include <bsd.kmod.mk>
