# $FreeBSD: src/sys/modules/sound/driver/ad1816/Makefile,v 1.1 2000/07/04 23:32:02 cg Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/isa

KMOD=	snd_ad1816
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	ad1816.c

.include <bsd.kmod.mk>
