# $FreeBSD: src/sys/modules/mlx/Makefile,v 1.6 2000/05/27 01:13:53 peter Exp $

.PATH: ${.CURDIR}/../../dev/mlx

KMOD=	mlx
SRCS=	mlx.c mlx_pci.c mlx_disk.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
