# $FreeBSD: src/sys/modules/sound/driver/sb8/Makefile,v 1.1 2000/10/28 19:28:49 cg Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/isa

KMOD=	snd_sb8
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	sb8.c

.include <bsd.kmod.mk>
